import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useForm } from '@mantine/form'
import { Box, Button, Container, Stack, Text, Textarea } from '@mantine/core'
import { useOpenAiQuery } from '@/react-query/useOpenAiQuery'
import { ChatCompletionResponseMessage } from 'openai'
import { KeyboardEventHandler, useRef, useState } from 'react'
import { Message } from './components/message'
import { codeSnippetsFormattingInstructionMessage } from '@/instructions/instructions'
import { WrappedMessage } from '@/types'

const wrapInWrappedMessage = (
  message: ChatCompletionResponseMessage,
  hidden = false
) => ({
  message: message,
  hidden,
})

export default function Home() {
  const { mutateAsync: sendMessages } = useOpenAiQuery()

  const [wrappedMessages, setWrappedMessages] = useState<WrappedMessage[]>([
    codeSnippetsFormattingInstructionMessage,
  ])

  const form = useForm({
    initialValues: {
      prompt:
        'Hey there, this is just a test prompt. But anyways nice chatting with you.',
    },
  })

  const handleButtonClick = async () => {
    const wrappedMessage = wrapInWrappedMessage({
      content: form.values.prompt,
      role: 'user',
    })
    form.setFieldValue('prompt', '')

    wrappedMessages.push(wrappedMessage)
    const responseMessage = await sendMessages(wrappedMessages)
    const newMessage = responseMessage.at(-1)
    setWrappedMessages((old) =>
      newMessage != null ? [...old, wrapInWrappedMessage(newMessage)] : old
    )
  }

  const handleClear = () => {
    setWrappedMessages([])
  }

  const mantineButtonRef = useRef<HTMLButtonElement>(null)

  const handleKeyPress: KeyboardEventHandler<HTMLTextAreaElement> = (event) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      mantineButtonRef.current?.click()
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container fluid sx={{ width: '100%' }}>
          <Box component="form" onSubmit={form.onSubmit(handleButtonClick)}>
            <Stack>
              <Stack spacing={4}>
                {wrappedMessages
                  .map((wrappedMessage, index) => {
                    if (wrappedMessage.hidden) return null
                    return (
                      <Message wrappedMessage={wrappedMessage} key={index} />
                    )
                  })
                  .filter(Boolean)}
              </Stack>

              <Textarea
                //
                label="Prompt"
                {...form.getInputProps('prompt')}
                placeholder="This is a test prompt"
                onKeyDown={handleKeyPress}
              />

              <Button
                //
                ref={mantineButtonRef}
                type="submit"
              >
                Submit
              </Button>

              <Text
                onClick={handleClear}
                component="a"
                align="center"
                size="sm"
                fw="bold"
                sx={{
                  cursor: 'pointer',
                  '&:hover': {
                    textDecoration: 'underline',
                  },
                }}
              >
                Clear conversation
              </Text>
            </Stack>
          </Box>
        </Container>
      </main>
    </>
  )
}
